-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ValidatorConfig" (
    "validatorId" TEXT NOT NULL PRIMARY KEY,
    "migrationId" INTEGER,
    "sponsorSvUrl" TEXT,
    "scanUrl" TEXT,
    "sequencerUrl" TEXT,
    "onboardingSecret" TEXT,
    "partyHint" TEXT,
    "disableBft" BOOLEAN NOT NULL DEFAULT true,
    "authEnabled" BOOLEAN NOT NULL DEFAULT false,
    "authUrl" TEXT,
    "authJwksUrl" TEXT,
    "authWellknownUrl" TEXT,
    "ledgerApiAudience" TEXT,
    "ledgerApiScope" TEXT,
    "ledgerApiAdminUser" TEXT,
    "validatorAudience" TEXT,
    "validatorClientId" TEXT,
    "validatorClientSecret" TEXT,
    "walletAdminUser" TEXT,
    "walletUiClientId" TEXT,
    "ansUiClientId" TEXT,
    "contactPoint" TEXT,
    "publicAccessMode" TEXT NOT NULL DEFAULT 'direct',
    "routingMode" TEXT NOT NULL DEFAULT 'multi',
    "baseDomain" TEXT,
    "enableWallet" BOOLEAN NOT NULL DEFAULT true,
    "walletSubdomain" TEXT DEFAULT 'wallet',
    "enableAns" BOOLEAN NOT NULL DEFAULT true,
    "ansSubdomain" TEXT DEFAULT 'ans',
    "enableApi" BOOLEAN NOT NULL DEFAULT true,
    "apiSubdomain" TEXT DEFAULT 'api',
    "enableMetrics" BOOLEAN NOT NULL DEFAULT false,
    "metricsSubdomain" TEXT DEFAULT 'metrics',
    "enableGrpcLedger" BOOLEAN NOT NULL DEFAULT false,
    "grpcLedgerSubdomain" TEXT DEFAULT 'grpc',
    "portLedgerApi" INTEGER DEFAULT 5001,
    "portWalletUi" INTEGER DEFAULT 2000,
    "portJsonApi" INTEGER DEFAULT 7575,
    "portValidatorApi" INTEGER DEFAULT 5003,
    "portSpliceNginx" INTEGER DEFAULT 8080,
    "walletDomain" TEXT,
    "ansDomain" TEXT,
    "validatorDomain" TEXT,
    "sslEnabled" BOOLEAN NOT NULL DEFAULT false,
    "sslEmail" TEXT,
    "nginxDeployedAt" DATETIME,
    "proxyHost" TEXT,
    "proxyPort" INTEGER,
    "autoTopUpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "trafficThroughput" INTEGER DEFAULT 200000,
    "trafficTopupInterval" TEXT DEFAULT '1m',
    "configuredAt" DATETIME,
    "firstStartedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ValidatorConfig_validatorId_fkey" FOREIGN KEY ("validatorId") REFERENCES "Validator" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_ValidatorConfig" ("ansDomain", "ansSubdomain", "ansUiClientId", "apiSubdomain", "authEnabled", "authJwksUrl", "authUrl", "authWellknownUrl", "baseDomain", "configuredAt", "contactPoint", "createdAt", "disableBft", "enableAns", "enableApi", "enableGrpcLedger", "enableMetrics", "enableWallet", "firstStartedAt", "grpcLedgerSubdomain", "ledgerApiAdminUser", "ledgerApiAudience", "ledgerApiScope", "metricsSubdomain", "migrationId", "nginxDeployedAt", "onboardingSecret", "partyHint", "portJsonApi", "portLedgerApi", "portSpliceNginx", "portValidatorApi", "portWalletUi", "proxyHost", "proxyPort", "publicAccessMode", "routingMode", "scanUrl", "sequencerUrl", "sponsorSvUrl", "sslEmail", "sslEnabled", "trafficThroughput", "trafficTopupInterval", "updatedAt", "validatorAudience", "validatorClientId", "validatorClientSecret", "validatorDomain", "validatorId", "walletAdminUser", "walletDomain", "walletSubdomain", "walletUiClientId") SELECT "ansDomain", "ansSubdomain", "ansUiClientId", "apiSubdomain", "authEnabled", "authJwksUrl", "authUrl", "authWellknownUrl", "baseDomain", "configuredAt", "contactPoint", "createdAt", "disableBft", "enableAns", "enableApi", "enableGrpcLedger", "enableMetrics", "enableWallet", "firstStartedAt", "grpcLedgerSubdomain", "ledgerApiAdminUser", "ledgerApiAudience", "ledgerApiScope", "metricsSubdomain", "migrationId", "nginxDeployedAt", "onboardingSecret", "partyHint", "portJsonApi", "portLedgerApi", "portSpliceNginx", "portValidatorApi", "portWalletUi", "proxyHost", "proxyPort", "publicAccessMode", "routingMode", "scanUrl", "sequencerUrl", "sponsorSvUrl", "sslEmail", "sslEnabled", "trafficThroughput", "trafficTopupInterval", "updatedAt", "validatorAudience", "validatorClientId", "validatorClientSecret", "validatorDomain", "validatorId", "walletAdminUser", "walletDomain", "walletSubdomain", "walletUiClientId" FROM "ValidatorConfig";
DROP TABLE "ValidatorConfig";
ALTER TABLE "new_ValidatorConfig" RENAME TO "ValidatorConfig";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
