import { Client } from 'ssh2'

import { prisma } from '@/lib/prisma'

type Validator = {
  host: string
  sshPort: number
  sshUsername: string
  sshAuthType: string
  sshPassword: string | null
  sshPrivateKey: string | null
}

function connectSSH(v: Validator): Promise<Client> {
  return new Promise((resolve, reject) => {
    const conn = new Client()
    const timeout = setTimeout(() => { conn.end(); reject(new Error('SSH connection timed out')) }, 30000)

    conn.on('ready', () => { clearTimeout(timeout); resolve(conn) })
    conn.on('error', err => { clearTimeout(timeout); reject(err) })

    const config: Record<string, unknown> = {
      host: v.host,
      port: v.sshPort,
      username: v.sshUsername,
      readyTimeout: 15000,
      keepaliveInterval: 5000,
      keepaliveCountMax: 20
    }

    if (v.sshAuthType === 'password') config.password = v.sshPassword
    else config.privateKey = v.sshPrivateKey

    conn.connect(config as Parameters<Client['connect']>[0])
  })
}

function execStream(conn: Client, cmd: string, onChunk?: (s: string) => void): Promise<{ code: number; output: string }> {
  return new Promise((resolve, reject) => {
    conn.exec(cmd, (err, stream) => {
      if (err) return reject(err)

      let output = ''

      stream.on('data', (d: Buffer) => {
        const c = d.toString()

        output += c; onChunk?.(c)
      })

      stream.stderr.on('data', (d: Buffer) => {
        const c = d.toString()

        output += c; onChunk?.(c)
      })
      stream.on('close', (code: number) => resolve({ code, output: output.trim() }))
    })
  })
}

// Build an nginx server block per FQDN. In domain mode the host nginx
// reverse-proxies into the Splice internal nginx (bound to 127.0.0.1:<spliceNginxPort>),
// which routes by Host header (wallet.localhost, ans.localhost, ...). We must
// therefore (1) point upstream to the splice-nginx port and (2) override the
// Host header to the matching `*.localhost` value.
//
// When SSL is enabled, the wallet/ANS UI bundles inside Splice still embed
// absolute http://<fqdn> URLs in their splice_config.json (Splice does not
// know its public scheme at container start). We therefore:
//   - add `Content-Security-Policy: upgrade-insecure-requests` so browsers
//     auto-upgrade any http://<fqdn>/* fetch to https,
//   - add `Strict-Transport-Security` so subsequent visits stay on https,
//   - rewrite Location response headers via proxy_redirect, and
//   - rewrite absolute http URLs inside text bodies (HTML/JSON/JS) via
//     sub_filter (requires Accept-Encoding stripped so upstream doesn't gzip).
function renderNginx(opts: {
  routingMode: 'multi' | 'path'
  baseDomain: string
  spliceNginxPort: number
  sslEnabled: boolean
  services: Array<{ name: string; fqdn: string; pathPrefix: string; spliceHost: string; ws?: boolean; directPort?: number }>
}): string {
  const { routingMode, baseDomain, spliceNginxPort, sslEnabled, services } = opts

  const upstream = `http://127.0.0.1:${spliceNginxPort}`

  const buildHeaders = (spliceHost: string, fqdn: string) => `
    proxy_http_version 1.1;
    proxy_set_header Host ${spliceHost};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Accept-Encoding "";
    proxy_read_timeout 300s;
    proxy_redirect http://${spliceHost}/ $scheme://${fqdn}/;
    proxy_redirect http://${fqdn}/ $scheme://${fqdn}/;${sslEnabled ? `
    sub_filter_once off;
    sub_filter_types application/json application/javascript text/html text/css text/javascript;
    sub_filter "http://${fqdn}" "https://${fqdn}";
    sub_filter "http:\\\\/\\\\/${fqdn}" "https:\\\\/\\\\/${fqdn}";` : ''}`

  // Headers added at the server-level (mixed-content mitigation). Browsers will
  // automatically rewrite http://<same-host>/* requests issued by page JS to
  // https when this CSP directive is present.
  const securityHeaders = sslEnabled ? `
  add_header Content-Security-Policy "upgrade-insecure-requests" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;` : ''

  if (routingMode === 'path') {
    const locations = services.map(s => `
  location ${s.pathPrefix}/ {
    proxy_pass ${upstream}/;${buildHeaders(s.spliceHost, baseDomain)}
  }`).join('\n')

    return `# Generated by NodePilot — do not edit by hand
server {
  listen 80;
  server_name ${baseDomain};${securityHeaders}
${locations}
}
`
  }

  // multi-subdomain
  return services.map(s => {
    const proxyTarget = s.directPort
      ? `http://127.0.0.1:${s.directPort}`
      : upstream

    // For direct-port services (e.g. Keycloak), pass the real hostname ($host)
    // instead of the internal spliceHost — otherwise Keycloak builds redirect
    // URIs pointing to localhost:8180.
    const effectiveSpliceHost = s.directPort ? '$host' : s.spliceHost

    return `# ${s.name}
server {
  listen 80;
  server_name ${s.fqdn};${securityHeaders}
  location / {
    proxy_pass ${proxyTarget};${buildHeaders(effectiveSpliceHost, s.fqdn)}
  }
}
`
  }).join('\n')
}

// POST /api/validators/[id]/configure-domain
// Streams Server-Sent Events with progress logs.
// Reads ValidatorConfig stage-5 fields, renders /etc/nginx/sites-available/<id>,
// reloads nginx, and (if sslEnabled) runs certbot --nginx for every FQDN.
export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params

  const validator = await prisma.validator.findUnique({ where: { id } })

  if (!validator) {
    return new Response(JSON.stringify({ error: 'Validator not found' }), { status: 404 })
  }

  const config = await prisma.validatorConfig.findUnique({ where: { validatorId: id } })

  if (!config || config.publicAccessMode !== 'domain' || !config.baseDomain) {
    return new Response(
      JSON.stringify({ error: 'Public access not configured for domain mode' }),
      { status: 400 }
    )
  }

  const encoder = new TextEncoder()

  const stream = new ReadableStream({
    async start(controller) {
      const log = (level: 'info' | 'warn' | 'error' | 'stdout' | 'stderr' | 'success', message: string) => {
        controller.enqueue(encoder.encode(
          `data: ${JSON.stringify({ timestamp: new Date().toISOString(), level, message })}\n\n`
        ))
      }

      const summary = (payload: Record<string, unknown>) => {
        controller.enqueue(encoder.encode(
          `data: ${JSON.stringify({ timestamp: new Date().toISOString(), kind: 'summary', ...payload })}\n\n`
        ))
      }

      const done = () => {
        if (closed) return
        closed = true
        controller.enqueue(encoder.encode(`data: ${JSON.stringify({ message: '__DONE__' })}\n\n`))
        controller.close()
      }

      let conn: Client | null = null
      let hadError = false
      let closed = false

      try {
        log('info', `Connecting to ${validator.host}:${validator.sshPort}…`)
        conn = await connectSSH(validator)
        log('success', '✓ SSH connected')

        // 1. Ensure nginx + certbot installed (idempotent; quiet if already there)
        // Wait for any existing apt/dpkg lock to be released first (up to 120s).
        log('info', 'Waiting for apt/dpkg lock (if held by another process)…')

        await execStream(conn,
          'for i in $(seq 1 60); do ' +
          'fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || break; ' +
          'sleep 2; done',
          c => log('stdout', c.trim()))

        log('info', 'Ensuring nginx and certbot are installed…')

        const inst = await execStream(conn,
          'DEBIAN_FRONTEND=noninteractive apt-get update -qq && ' +
          'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx certbot python3-certbot-nginx python3-pip && ' +

          // Debian 12 ships certbot 2.1.0 which has a fatal
          // "AttributeError: can't set attribute" bug when using --nginx.
          // Always upgrade via pip to get a working version. The pip
          // version takes precedence over the apt version in $PATH.
          '(pip3 install --break-system-packages --upgrade certbot certbot-nginx 2>&1 || ' +
          'pip3 install --upgrade certbot certbot-nginx 2>&1) && ' +
          'hash -r && ' +  // refresh shell's command cache so new certbot is found
          'certbot --version 2>&1',
          c => log('stdout', c.trim()))

        if (inst.code !== 0) {
          log('error', `apt-get failed (exit ${inst.code}). Last output:\n${inst.output.split('\n').slice(-10).join('\n')}`)
          hadError = true
          summary({ ok: false, stage: 'apt-install' })
          done()

          return
        }

        log('success', '✓ nginx + certbot present')

        // 1b. Ensure splice-nginx container is NOT binding to host port 80.
        // In domain mode, host nginx needs port 80/443 and proxies to
        // splice-nginx on 127.0.0.1:8080. If the validator was started
        // before domain mode was configured (or via an older Nodepilot),
        // splice-nginx may still be on 0.0.0.0:80 → host nginx can't start.
        // Fix: remap compose to 127.0.0.1:8080:80 and recreate the container.
        if (validator.installPath) {
          const validatorRoot = `${validator.installPath}/docker-compose/validator`
          const internalPort = config.portSpliceNginx ?? 8080

          log('info', 'Checking if splice-nginx needs port remap (80 → loopback)…')

          const checkPort80 = await execStream(conn,
            `docker port splice-validator-nginx-1 80 2>/dev/null | grep -q '0.0.0.0:80' && echo NEEDS_REMAP || echo OK`)

          if (checkPort80.output.includes('NEEDS_REMAP')) {
            log('warn', `splice-nginx is bound to 0.0.0.0:80 — remapping to 127.0.0.1:${internalPort}…`)

            const remapCmd = [
              `cd ${validatorRoot}`,
              `COMPOSE_FILE=$(ls compose.yaml compose-validator.yaml docker-compose.yaml 2>/dev/null | head -1)`,
              `if [ -z "$COMPOSE_FILE" ]; then echo "ERROR: no compose file found" >&2; exit 1; fi`,
              `cp -n "$COMPOSE_FILE" "$COMPOSE_FILE.bak" 2>/dev/null || true`,
              `sed -i -E ` +
                `-e 's@\\$\\{HOST_BIND_IP:-127\\.0\\.0\\.1\\}:80:80@127.0.0.1:${internalPort}:80@' ` +
                `-e 's@"0\\.0\\.0\\.0:80:80"@"127.0.0.1:${internalPort}:80"@' ` +
                `-e 's@"127\\.0\\.0\\.1:80:80"@"127.0.0.1:${internalPort}:80"@' ` +
                `-e 's@^([[:space:]]*-[[:space:]]*)"80:80"@\\1"127.0.0.1:${internalPort}:80"@' ` +
                `"$COMPOSE_FILE"`,
              `cd ${validatorRoot} && docker compose up -d --no-deps nginx 2>&1`
            ].join(' && ')

            const remap = await execStream(conn, remapCmd, c => log('stdout', c.trim()))

            if (remap.code !== 0) {
              log('error', `Failed to remap splice-nginx (code ${remap.code}): ${remap.output.split('\n').slice(-5).join('\n')}`)
              hadError = true
              summary({ ok: false, stage: 'splice-nginx-remap' })
              done()

              return
            }

            // Wait a moment for the container to be recreated
            await new Promise(r => setTimeout(r, 3000))
            log('success', `✓ splice-nginx remapped to 127.0.0.1:${internalPort} — port 80 freed for host nginx`)
          } else {
            log('info', '✓ splice-nginx already on loopback (not blocking port 80)')
          }
        }

        // 2. Pre-flight: check if splice-nginx is running. This is informational
        // only — nginx config + SSL cert can be deployed without it. Subdomains
        // will 502 until the validator starts, but that's fine (user can start
        // after domain is set up, especially for first OIDC setup).
        const spliceNginxPort = config.portSpliceNginx ?? 8080

        log('info', `Pre-flight: checking splice-nginx on 127.0.0.1:${spliceNginxPort}…`)

        const preflight = await execStream(conn,
          `ss -ltn 'sport = :${spliceNginxPort}' | tail -n +2 | grep -q . && echo OK || echo MISSING`)

        const spliceNginxRunning = preflight.output.includes('OK')

        if (!spliceNginxRunning) {
          log('warn',
            `Splice-nginx is not running on port ${spliceNginxPort} — validator may not be started yet. ` +
            `Continuing with nginx config and SSL deployment. ` +
            `Subdomains will work once the validator is started.`)
        } else {
          log('success', `✓ splice-nginx is listening on 127.0.0.1:${spliceNginxPort}`)
        }

        // 3. Build service list from config
        const fqdn = (sub: string | null, enabled: boolean) => {
          if (!enabled) return null
          if (config.routingMode === 'path') return config.baseDomain

          return sub ? `${sub}.${config.baseDomain}` : config.baseDomain
        }

        const services = ([
          { name: 'wallet', enabled: config.enableWallet, sub: config.walletSubdomain, spliceHost: 'wallet.localhost', path: '/wallet', probe: '/' },
          { name: 'ans', enabled: config.enableAns, sub: config.ansSubdomain, spliceHost: 'ans.localhost', path: '/ans', probe: '/' },
          { name: 'api', enabled: config.enableApi, sub: config.apiSubdomain, spliceHost: 'json-ledger-api.localhost', path: '/api', probe: '/v2/version' },
          { name: 'metrics', enabled: config.enableMetrics, sub: config.metricsSubdomain, spliceHost: 'validator.localhost', path: '/metrics', probe: '/metrics' },
          { name: 'grpc', enabled: config.enableGrpcLedger, sub: config.grpcLedgerSubdomain, spliceHost: 'grpc-ledger-api.localhost', path: '/grpc', probe: null },

          // Keycloak: proxied directly to its container port (not through splice-nginx)
          { name: 'keycloak', enabled: !!config.enableKeycloak, sub: config.keycloakSubdomain, spliceHost: `localhost:${config.keycloakPort ?? 8180}`, path: '/keycloak', probe: '/realms/master', directPort: config.keycloakPort ?? 8180 }
        ])
          .filter(s => s.enabled)
          .map(s => ({
            name: s.name,
            fqdn: fqdn(s.sub, true)!,
            pathPrefix: s.path,
            spliceHost: s.spliceHost,
            probe: s.probe,
            ...('directPort' in s ? { directPort: s.directPort } : {})
          }))

        if (services.length === 0) {
          log('error', 'No services enabled — nothing to deploy. Enable at least Wallet under Public Access.')
          hadError = true
          summary({ ok: false, stage: 'no-services' })
          done()

          return
        }

        log('info', `Deploying ${services.length} service(s): ${services.map(s => s.name).join(', ')}`)

        const nginxConf = renderNginx({
          routingMode: (config.routingMode as 'multi' | 'path') ?? 'multi',
          baseDomain: config.baseDomain!,
          spliceNginxPort,
          sslEnabled: !!config.sslEnabled,
          services
        })

        // 4. Write the config (heredoc is safe for our generated output — no untrusted content)
        const sitePath = `/etc/nginx/sites-available/nodepilot-${id}`
        const linkPath = `/etc/nginx/sites-enabled/nodepilot-${id}`

        log('info', `Writing nginx config → ${sitePath}`)

        const writeCmd = `cat > ${sitePath} <<'NGINXEOF'\n${nginxConf}\nNGINXEOF\n` +
          `ln -sf ${sitePath} ${linkPath} && nginx -t 2>&1`

        const w = await execStream(conn, writeCmd, c => log('stdout', c.trim()))

        if (w.code !== 0) {
          log('error', `nginx -t failed (exit ${w.code}). Output:\n${w.output}`)
          hadError = true
          summary({ ok: false, stage: 'nginx-test' })
          done()

          return
        }

        log('success', '✓ nginx config valid')

        // 5. Start or reload nginx — reload is graceful but only works if
        //    nginx is already active. On a fresh VPS, the service has never
        //    been started, so `reload` fails with "not active, cannot reload".
        log('info', 'Starting/reloading nginx…')

        const reload = await execStream(conn,
          'if systemctl is-active --quiet nginx; then systemctl reload nginx 2>&1; else systemctl start nginx 2>&1; fi',
          c => log('stdout', c.trim()))

        if (reload.code !== 0) {
          log('error', `nginx reload failed (exit ${reload.code}). Output:\n${reload.output}`)
          hadError = true
          summary({ ok: false, stage: 'nginx-reload' })
          done()

          return
        }

        log('success', '✓ nginx reloaded')

        // 6. SSL setup — either use a stored certificate or generate via certbot
        if (config.sslEnabled) {
          // Remove the Ubuntu default site to prevent certbot/nginx conflicts
          await execStream(conn,
            'rm -f /etc/nginx/sites-enabled/default && nginx -t 2>/dev/null && (systemctl is-active --quiet nginx && systemctl reload nginx || systemctl start nginx) 2>/dev/null || true')

          if (config.sslCertificateId) {
            // 6a. Use stored certificate from database
            const storedCert = await prisma.sslCertificate.findUnique({
              where: { id: config.sslCertificateId }
            })

            if (!storedCert) {
              log('error', 'Stored SSL certificate not found — re-select a certificate in SSL settings')
              hadError = true
              summary({ ok: false, stage: 'ssl-stored' })
              done()

              return
            }

            log('info', `Deploying stored SSL certificate "${storedCert.label}" (${storedCert.domains})…`)

            // Write cert + key to files on VPS using base64 to avoid
            // any shell escaping / heredoc issues with PEM content.
            const certPath = `/etc/ssl/nodepilot/${id}`

            await execStream(conn, `mkdir -p ${certPath}`)

            const certB64 = Buffer.from(storedCert.certPem).toString('base64')
            const keyB64 = Buffer.from(storedCert.keyPem).toString('base64')

            const writeCert = await execStream(conn,
              `echo '${certB64}' | base64 -d > ${certPath}/fullchain.pem`)

            if (writeCert.code !== 0) {
              log('error', `Failed to write fullchain.pem: ${writeCert.output}`)
              hadError = true
              summary({ ok: false, stage: 'ssl-write' })
              done()

              return
            }

            const writeKey = await execStream(conn,
              `echo '${keyB64}' | base64 -d > ${certPath}/privkey.pem && chmod 600 ${certPath}/privkey.pem`)

            if (writeKey.code !== 0) {
              log('error', `Failed to write privkey.pem: ${writeKey.output}`)
              hadError = true
              summary({ ok: false, stage: 'ssl-write' })
              done()

              return
            }

            // Verify files were written
            const verifyFiles = await execStream(conn,
              `test -s ${certPath}/fullchain.pem && test -s ${certPath}/privkey.pem && echo OK`)

            if (!verifyFiles.output.includes('OK')) {
              log('error', 'SSL cert/key files are empty after write')
              hadError = true
              summary({ ok: false, stage: 'ssl-write' })
              done()

              return
            }

            log('stdout', `Wrote cert (${storedCert.certPem.length} bytes) + key (${storedCert.keyPem.length} bytes) to ${certPath}/`)

            // Instead of patching the existing config (which causes duplicate
            // MIME types and fragile inline edits), write a dedicated SSL
            // overlay that nginx includes alongside the HTTP config.
            const fqdns = services.map(s => s.fqdn)
            const serverNames = fqdns.join(' ')
            const sslConf = `/etc/nginx/sites-available/nodepilot-${id}-ssl`
            const sslLink = `/etc/nginx/sites-enabled/nodepilot-${id}-ssl`

            // Build SSL server blocks — one per upstream service, mirroring
            // the location blocks from the HTTP config but on port 443.
            const upstream = `http://127.0.0.1:${spliceNginxPort}`

            const sslServerBlocks = services.map(s => {
              const proxyTarget = s.directPort
                ? `http://127.0.0.1:${s.directPort}`
                : upstream

              const effectiveHost = s.directPort ? '$host' : s.spliceHost

              return [
                `# ${s.name}`,
                `server {`,
                `  listen 443 ssl;`,
                `  listen [::]:443 ssl;`,
                `  server_name ${s.fqdn};`,
                ``,
                `  ssl_certificate ${certPath}/fullchain.pem;`,
                `  ssl_certificate_key ${certPath}/privkey.pem;`,
                `  ssl_protocols TLSv1.2 TLSv1.3;`,
                `  ssl_ciphers HIGH:!aNULL:!MD5;`,
                ``,
                `  add_header Content-Security-Policy "upgrade-insecure-requests" always;`,
                `  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;`,
                ``,
                `  location / {`,
                `    proxy_pass ${proxyTarget};`,
                `    proxy_http_version 1.1;`,
                `    proxy_set_header Host ${effectiveHost};`,
                `    proxy_set_header X-Real-IP $remote_addr;`,
                `    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
                `    proxy_set_header X-Forwarded-Host $host;`,
                `    proxy_set_header X-Forwarded-Proto $scheme;`,
                `    proxy_set_header Upgrade $http_upgrade;`,
                `    proxy_set_header Connection "upgrade";`,
                `    proxy_set_header Accept-Encoding "";`,
                `    proxy_read_timeout 300s;`,
                `    proxy_redirect http://${effectiveHost}/ $scheme://${s.fqdn}/;`,
                `    proxy_redirect http://${s.fqdn}/ $scheme://${s.fqdn}/;`,
                `    sub_filter_once off;`,
                `    sub_filter_types application/json application/javascript text/html text/css text/javascript;`,
                `    sub_filter "http://${s.fqdn}" "https://${s.fqdn}";`,
                `    sub_filter "http:\\\\/\\\\/${s.fqdn}" "https:\\\\/\\\\/${s.fqdn}";`,
                `  }`,
                `}`
              ].join('\n')
            }).join('\n\n')

            // HTTP→HTTPS redirect
            const redirectBlock = [
              `# HTTP → HTTPS redirect (NodePilot)`,
              `server {`,
              `  listen 80;`,
              `  listen [::]:80;`,
              `  server_name ${serverNames};`,
              `  return 301 https://$host$request_uri;`,
              `}`
            ].join('\n')

            const sslFullConfig = `# NodePilot SSL config — auto-generated\n${sslServerBlocks}\n\n${redirectBlock}\n`

            const sslB64 = Buffer.from(sslFullConfig).toString('base64')

            const writeSslConf = await execStream(conn,
              `echo '${sslB64}' | base64 -d > ${sslConf} && ln -sf ${sslConf} ${sslLink}`)

            if (writeSslConf.code !== 0) {
              log('error', `Failed to write SSL nginx config: ${writeSslConf.output}`)
              hadError = true
              summary({ ok: false, stage: 'ssl-nginx-config' })
              done()

              return
            }

            // Remove the HTTP-only listen 80 from the main site config since
            // the SSL overlay now handles both 443 and the 80→443 redirect.
            await execStream(conn,
              `rm -f /etc/nginx/sites-enabled/nodepilot-${id}`)

            const sslTest = await execStream(conn, 'nginx -t 2>&1')

            if (sslTest.code !== 0) {
              log('error', `nginx -t failed after SSL config: ${sslTest.output}`)
              hadError = true
              summary({ ok: false, stage: 'ssl-nginx-test' })
              done()

              return
            }

            await execStream(conn, 'if systemctl is-active --quiet nginx; then systemctl reload nginx; else systemctl start nginx; fi')
            log('success', `✓ SSL deployed from stored certificate "${storedCert.label}"`)
          } else if (config.sslEmail) {
            // 6b. Generate via Let's Encrypt (certbot)
            const fqdns = services.map(s => s.fqdn)

            const dArgs = fqdns.map(f => `-d ${f}`).join(' ')

            log('info', `Requesting Let's Encrypt cert for ${fqdns.length} FQDN(s)…`)

            const cb = await execStream(conn,
              `certbot --nginx --non-interactive --agree-tos --expand -m ${config.sslEmail} ${dArgs} --redirect 2>&1`,
              c => log('stdout', c.trim()))

            if (cb.code !== 0) {
              const tail = cb.output.split('\n').slice(-15).join('\n')

              log('error',
                `certbot failed (exit ${cb.code}). Common causes: ` +
                `(a) DNS A-record missing or pointing elsewhere — verify with the DNS Check button. ` +
                `(b) Port 80 not reachable from the internet (firewall / cloud security group). ` +
                `(c) Rate limit hit on Let's Encrypt. Last output:\n${tail}`)
              hadError = true
              summary({ ok: false, stage: 'certbot' })
              done()

              return
            }

            log('success', '✓ SSL cert installed via Let\'s Encrypt')

            // Store the generated cert in database for future reuse
            const fqdnList = fqdns.join(', ')

            log('info', 'Saving Let\'s Encrypt cert to database for reuse…')

            const readCert = await execStream(conn,
              `cat /etc/letsencrypt/live/$(ls /etc/letsencrypt/live/ | grep -v README | head -1)/fullchain.pem 2>/dev/null`)

            const readKey = await execStream(conn,
              `cat /etc/letsencrypt/live/$(ls /etc/letsencrypt/live/ | grep -v README | head -1)/privkey.pem 2>/dev/null`)

            if (readCert.code === 0 && readKey.code === 0 && readCert.output.includes('BEGIN')) {
              const saved = await prisma.sslCertificate.create({
                data: {
                  label: `Let's Encrypt — ${config.baseDomain}`,
                  domains: fqdnList,
                  source: 'letsencrypt',
                  certPem: readCert.output,
                  keyPem: readKey.output
                }
              })

              // Link to this validator
              await prisma.validatorConfig.update({
                where: { validatorId: id },
                data: { sslCertificateId: saved.id }
              })

              log('success', `✓ Cert saved to database (ID: ${saved.id}) — can be reused by other validators`)
            }

            // Verify certbot didn't re-create a conflicting default site
            await execStream(conn,
              'rm -f /etc/nginx/sites-enabled/default && nginx -t 2>/dev/null && (systemctl is-active --quiet nginx && systemctl reload nginx || systemctl start nginx) 2>/dev/null || true')
          } else {
            log('warn', 'SSL enabled but no email and no stored certificate — skipping SSL setup')
          }
        } else {
          log('info', 'SSL not requested — skipping (HTTP only)')
        }

        // 7. Post-deploy smoke test — skipped if splice-nginx is not running yet.
        // (User may be doing first-time domain setup before starting the validator.)
        const probes: Array<{ name: string; fqdn: string; url: string; code: number; ok: boolean }> = []

        if (!spliceNginxRunning) {
          log('info', 'Skipping smoke test — validator not started yet. Start it to verify subdomains are reachable.')
        } else {
          log('info', 'Running post-deploy smoke test…')

          const scheme = config.sslEnabled ? 'https' : 'http'
          const curlFlag = config.sslEnabled ? '-sk' : '-s'

          for (const s of services) {
            if (!s.probe) {
              log('info', `→ ${s.name} (${s.fqdn}): skipped (gRPC, requires HTTP/2 client)`)
              continue
            }

            // For services proxied directly to a local container port (e.g. Keycloak),
            // skip with a warning when that container isn't running yet. This lets the
            // user configure the domain BEFORE deploying the backing service.
            if (s.directPort) {
              const portCheck = await execStream(conn,
                `ss -ltn 'sport = :${s.directPort}' | tail -n +2 | grep -q . && echo OK || echo MISSING`)

              if (!portCheck.output.includes('OK')) {
                log('warn',
                  `→ ${s.name.padEnd(8)} ${s.fqdn}${s.probe}: skipped — nothing listening on 127.0.0.1:${s.directPort}. ` +
                  `Deploy ${s.name} from NodePilot to activate this subdomain.`)
                probes.push({ name: s.name, fqdn: s.fqdn, url: `${scheme}://${s.fqdn}${s.probe}`, code: 0, ok: false })
                continue
              }
            }

            const probeCmd =
              `curl ${curlFlag} -o /dev/null -w '%{http_code}' --max-time 8 ` +
              `-H 'Host: ${s.fqdn}' ${scheme}://127.0.0.1${s.probe}`

            const p = await execStream(conn, probeCmd)
            const code = parseInt(p.output.trim(), 10) || 0
            const ok = code >= 200 && code < 400

            probes.push({ name: s.name, fqdn: s.fqdn, url: `${scheme}://${s.fqdn}${s.probe}`, code, ok })

            if (ok) log('success', `✓ ${s.name.padEnd(8)} ${s.fqdn}${s.probe} → HTTP ${code}`)
            else { log('error', `✗ ${s.name.padEnd(8)} ${s.fqdn}${s.probe} → HTTP ${code} (expected 2xx/3xx)`); hadError = true }
          }
        }

        // 8. Mark deployed — succeed even if validator wasn't running (smoke test skipped).
        if (!hadError) {
          await prisma.validatorConfig.update({
            where: { validatorId: id },
            data: { nginxDeployedAt: new Date() }
          })
          log('success', '✅ Public access deployed and verified')
          summary({ ok: true, stage: 'done', probes })
        } else {
          log('error', 'Deploy completed with errors — see above. nginxDeployedAt not updated.')
          summary({ ok: false, stage: 'smoke-test', probes })
        }
      } catch (e) {
        log('error', `Unhandled error: ${e instanceof Error ? e.message : String(e)}`)
        hadError = true
        summary({ ok: false, stage: 'exception' })
      } finally {
        conn?.end()
        done()
      }
    }
  })

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive'
    }
  })
}
