-- CreateTable
CREATE TABLE "ValidatorConfig" (
    "validatorId" TEXT NOT NULL PRIMARY KEY,
    "migrationId" INTEGER,
    "sponsorSvUrl" TEXT,
    "onboardingSecret" TEXT,
    "partyHint" TEXT,
    "authEnabled" BOOLEAN NOT NULL DEFAULT false,
    "authUrl" TEXT,
    "authJwksUrl" TEXT,
    "authWellknownUrl" TEXT,
    "ledgerApiAudience" TEXT,
    "ledgerApiScope" TEXT,
    "ledgerApiAdminUser" TEXT,
    "validatorAudience" TEXT,
    "validatorClientId" TEXT,
    "validatorClientSecret" TEXT,
    "walletAdminUser" TEXT,
    "walletUiClientId" TEXT,
    "ansUiClientId" TEXT,
    "contactPoint" TEXT,
    "proxyHost" TEXT,
    "proxyPort" INTEGER,
    "trafficThroughput" INTEGER,
    "trafficTopupInterval" TEXT,
    "configuredAt" DATETIME,
    "firstStartedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ValidatorConfig_validatorId_fkey" FOREIGN KEY ("validatorId") REFERENCES "Validator" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
